trigger:
- master

variables:
  azureServiceConnection: 'AlongX-Azure-Account-Development'
  webAppName: 'gsm-webapp'
  vmImageName: 'ubuntu-latest'
  environmentName: 'gsm-webapp'
  pythonVersion: '3.12'
  isRelease: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

pool:
  vmImage: $(vmImageName)

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy'
  steps:
  - task: UsePythonVersion@0
    displayName: 'User Python Version'
    inputs:
      versionSpec: $(pythonVersion)  # Replace with your Python version

  - script: |
      python -m venv env
      source env/bin/activate
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  - task: ArchiveFiles@2
    displayName: 'Archive Files'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'drop'
      publishLocation: 'pipeline'

- deployment: DeployToAzureAppService
  displayName: 'Deploy to Azure App Service'
  environment: $(environmentName)  # Replace with your environment name
  condition: and(succeeded(), eq(variables.isRelease, true))
  strategy:
    runOnce:
      deploy:
        steps:
        - task: DownloadPipelineArtifact@2
          displayName: 'Download Pipeline Artifact'
          inputs:
            buildType: 'current'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'

        - task: AzureWebApp@1
          displayName: 'Deploy to Azure App Service'
          inputs:
            azureSubscription: $(azureServiceConnection)
            appType: 'webAppLinux'
            appName: $(webAppName)
            package: '$(System.ArtifactsDirectory)/**/*.zip'