trigger:
- develop

variables:
  azureServiceConnection: 'AlongX-Azure-Account-Development'
  webAppName: 'gsm-webapp'
  resourceGroupName: 'Development'
  vmImageName: 'ubuntu-latest'
  environmentName: 'gsm-webapp'
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: '3.12'
  isRelease: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]


stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        sudo apt install python3-venv
        python3 -m venv djangoenv
        source djangoenv/bin/activate
        python -m pip install django
        python -m pip install --upgrade pip
        pip install setup
        pip install -r requirements.txt
        python manage.py collectstatic --no-input
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: 'Deploy to Develop Environment'
  dependsOn: Build
  condition: and(succeeded(), eq(variables.isRelease, true))
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python version'
          
          - task: AzureAppServiceSettings@1
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appName: $(webAppName)
              resourceGroupName: '$(resourceGroupName)'
              appSettings: |
                [
                  {
                    "name": "ENABLE_ORYX_BUILD",
                    "value": 1
                  },
                  {
                    "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                    "value": 1
                  },
                  {
                    "name": "POST_BUILD_COMMAND",
                    "value": "pip install -r requirements.txt"
                  }
                ]

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : $(webAppName)'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appType: 'webAppLinux'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'

          # - task: AzureCLI@2
          #   displayName: 'Restart App Service'
          #   inputs:
          #     azureSubscription: '$(azureServiceConnection)'
          #     scriptType: 'bash'
          #     scriptLocation: 'inlineScript'
          #     inlineScript: |
          #       # Restart Azure App Service
          #       resourceGroupName='Development'
          #       webAppName='gsm-webapp'
          #       az webapp restart --resource-group $resourceGroupName --name $webAppName