# Generated by Django 5.0 on 2023-12-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_entry_date', models.DateField(auto_now=True)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=15)),
                ('payment_mode', models.CharField(max_length=25)),
                ('particular_name', models.CharField(max_length=255)),
                ('transaction_amount_debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_amount_credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255)),
                ('payment_reference', models.CharField(max_length=255)),
                ('net_balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
